version: '3'
networks:
  private:
    driver: overlay
services:
  hub:
    image: selenium/hub:3.7.1
    ports:
      - "4444:4444"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 30s
        max_attempts: 100
        window: 500s
    environment:
     - GRID_BROWSER_TIMEOUT=120000
     - GRID_TIMEOUT=120000
     - GRID_MAX_SESSION=100
     - GRID_CLEAN_UP_CYCLE=5000
    networks:
     - private

  chrome:
     image: selenium/node-chrome:3.7.1
     volumes:
       - /dev/urandom:/dev/random
       - /dev/shm:/dev/shm
     depends_on:
       - hub
     environment:
       - HUB_PORT_4444_TCP_ADDR=hub
       - HUB_PORT_4444_TCP_PORT=4444
     ports:
       - "5557:5556"
     entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5557" /opt/bin/entry_point.sh'
     networks:
       - private

  firefox:
    image: selenium/node-firefox:3.7.1
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5557:5556"
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5557" /opt/bin/entry_point.sh'
    networks:
      - private

  phantomjs:
    image: selenium/node-phantomjs:3.7.1
    volumes:
      - /dev/urandom:/dev/random
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 15
        window: 480s
    ports:
      - "5556:5556"
    networks:
      - private
